---
layout: exercises
title:  "Chapter 12: More Exercises"
---

## Chapter 12 - Recovering from Failure

### Exercise 1: `defer`

We need to be sure our `Camp` function calls the `Fire` value's `Extinguish` method before the program exits. But right now, `Camp` is returning early due to an error, before `Extinguish` can be called.

We don't want to leave a lit `Fire` unattended in the forest! Revise the `Camp` function so that `Extinguish` is always called, even if `Camp` returns early.

{% highlight go %}
package main

import "fmt"

type Fire struct {
	lit bool
}

func (f Fire) Light() {
	f.lit = true
	fmt.Println("Fire lit:", f.lit)
}
func (f Fire) Extinguish() {
	f.lit = false
	fmt.Println("Fire lit:", f.lit)
}

func Camp() error {
	var fire Fire
	fire.Light()
	return fmt.Errorf("spotted a bear")
	fmt.Println("Toasting marshmallows")
	fire.Extinguish()
	return nil
}

func main() {
	err := Camp()
	if err != nil {
		fmt.Println(err)
	}
}
{% endhighlight %}

Actual Output:

``` text
Fire lit: true
Error: spotted a bear
```

Desired Output:

``` text
Fire lit: true
Fire lit: false
Error: spotted a bear
```

When you're ready, have a look at [our solution](/solutions/ch12_01.html).
